### ISSUE TITLE
Packetfly [SUGGESTION]

### ISSUE THREAD

**Issue by Cyrogigabyte** [WurstPlus/wurst-plus-three#100]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [All of the crystalpvp.cc players laugh at me cuz I don't wanna get konas]

**Describe the solution you'd like**
Packetfly + Phase
**Describe alternatives you've considered**
No
**Additional context**

**Comment by Gaamr** [comment]
dont get konas its shit

**Comment by Officer32k** [comment]
@Gaamr die
