### ISSUE TITLE
Contributor tasks

### ISSUE THREAD

**Issue by YeahOMA** [WurstPlus/wurst-plus-three#114]
add a place where contributors can see what needs to be done so they can open up a pull request

**Comment by TrvsF** [comment]
should probably do this, the discord is a bit of a shithole atm

**Comment by wallhacks0** [comment]
@YeahOMA I have some stuff you could work on: 
 -yaw step
 -group settings 
 -cev breaker
 -onground speed
 -outlines in chams

**Comment by wallhacks0** [comment]
@TrvsF made this in to a place to keep track of stuff to do for now

**Comment by B2H990** [comment]
just use the todos already in the codebase

**Comment by TrvsF** [comment]
todos and the discord will do for now
