### ISSUE TITLE
Gamesense Compatibility

### ISSUE THREAD

**Issue by Ozynt** [WurstPlus/wurst-plus-three#123]
**Is your feature request related to a problem? Please describe.**
I would like if you made it work with gamesense. 

**Describe the solution you'd like**
I want it so I can run both clients at the same time.

**Describe alternatives you've considered**

Wurst+2 was working with gamesense so matbe its not to hard to get Wurst+3 to work with it. 

**Additional context**

**Comment by TediousDuskFall** [comment]
lmfao it works with gamesense?

**Comment by Osynt1** [comment]
Shown me how then, I have tried 2.2.8 and 2.3.0 none of them works...

**Comment by zihasz** [comment]
Works for me too 🤪

**Comment by zihasz** [comment]
Almost latest dev build

**Comment by Ozynt** [comment]
But what exact version?

**Comment by Officer32k** [comment]
d2.3.1

**Comment by Ozynt** [comment]
I found out what the problem was. If I use gamesense and w+3 and rusherhack at the same time it wont work. But if I dont use rusherhack it will load up.

**Comment by wallhacks0** [comment]
dm latest.txt wallhacks#6969 and make sure to not include personal info on accident il take a look at it.

**Comment by Ozynt** [comment]
> dm latest.txt wallhacks#6969 and make sure to not include personal info on accident il take a look at it.

Will do it tomorrow.

**Comment by w0rl3x** [comment]
lmao gamesense users in 2021 most useless hack ever

**Comment by dldlglglgluyl** [comment]
Facts ^

**Comment by TrvsF** [comment]
not sure what happened here, if it isn't 'fixed' reopen
