### ISSUE TITLE
good cilent

### ISSUE THREAD

**Issue by villkaa-2b2t** [WurstPlus/wurst-plus-three#124]
one of the best cilents you made. The crystal aura is gud the default version. Burrow is very help for me. Step and Speed is so helpful because speed makes me FASTTT and step doesn't glitch.

**Comment by Aholicknight** [comment]
what kind of issue is this??? do you know how github works

**Comment by RealzPrestige** [comment]
Thanks for reporting this issue, this will be taking very seriously since this seriously endanger this client's existance.
