### ISSUE TITLE
[BUG] Wurst+3 Randomly Crashes

### ISSUE THREAD

**Issue by uhhhhhhhhhhhhhhhhhhhhhh** [WurstPlus/wurst-plus-three#127]
**Randomly Crashes**

**Reproduce**
Steps to reproduce the behavior: Sometimes Toggleing using keybinds just closes it
1. Turn on module: 'N/A'
2. Set the setting to 'N/A'
3. See error

**Expected behavior**
to work like normal and not crash???

**Screenshots**
N/A

**Additional context**
N/A

**Comment by wallhacks0** [comment]
to help us solve random crashes please provide a crashlog

**Comment by cheeziest** [comment]
Dummy
