### ISSUE TITLE
[SUGGESTION] Andromeda toggle for Scaffold

### ISSUE THREAD

**Issue by wyvest** [WurstPlus/wurst-plus-three#128]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't bridge fast enough because of my stupid SCAFFOLD! **It's just not fast enough!** That's why I'm suggesting the ANDROMEDA FEATURE for scaffold. literally do it. a hypixel mod dev did it, if you can't you're bad at everything-

**Describe the solution you'd like**
Typically, scaffold just places below your feet. The Andromeda Mod (made by caterpillow), instead of adding _literal_ hacks, added _borderline hacks_ for whatever reason (I honestly don't know why)??? Thus, the mod isn't as fast as if you just jump sprinted in a 1x2x1 strip mine. This is why I propose literally just adding a block above your head, like scaffold, but backwards.

**Describe alternatives you've considered**
nothing.

**Additional context**
this sounds like an elaborate shitpost but this actually is a suggestion please add thanks :)

**Comment by cheeziest** [comment]
Dumb idea

**Comment by wallhacks0** [comment]
no pls no

**Comment by RealzPrestige** [comment]
this is just useless for anarchy clients ;/

**Comment by wyvest** [comment]
> no pls no

Yes

**Comment by wallhacks0** [comment]
no its a horrible idea
