### ISSUE TITLE
[SUGGESTION] double holes on hole esp and killaura for sword

### ISSUE THREAD

**Issue by cheeziest** [WurstPlus/wurst-plus-three#129]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [i get made fun of because i have to toggle KA whenever i wanna be a swordfriend, and also when i cant see double holes]

**Describe the solution you'd like**
Wp2 had killaura with sword and like every client has hole esp for doubles

**Describe alternatives you've considered**
I mean i could use another client but I’m too lazy
**Additional context**

**Comment by wallhacks0** [comment]
please please pleaaase delete the github issue format after reading it

**Comment by wallhacks0** [comment]
also both things are fixed on my local branch so by issue
