### ISSUE TITLE
Smart holefill

### ISSUE THREAD

**Issue by RealzPrestige** [WurstPlus/wurst-plus-three#132]
make holefill that when enemy is in range of hole 0-5 it will do holefill for that block only

**Comment by RealzPrestige** [comment]
like gondal <3 es0t

**Comment by wallhacks0** [comment]
phobos had this too lol

**Comment by RealzPrestige** [comment]
so add it yes

**Comment by RealzPrestige** [comment]
wait can i @everyone

**Comment by RealzPrestige** [comment]
nvm lol

**Comment by wallhacks0** [comment]
I really dont like this feature myself but il make it anyways

**Comment by RealzPrestige** [comment]
how can u not like it

**Comment by w0rl3x** [comment]
vethack 3.8 has it, so it wont be a high effort work to paste it

**Comment by wallhacks0** [comment]
and it will be even less work to do myself 🤦

**Comment by sixtieth2** [comment]
bro what
