### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by mememememememeWEEE** [WurstPlus/wurst-plus-three#133]
When I go on 2bpvp it's all fine, but then when the crystalaura starts to place crystals it suddenly crashes the game without and crash reports.

**Comment by wallhacks0** [comment]
if this happens again send latest.txt its located in logs folder

**Comment by mememememememeWEEE** [comment]
[latest.log](https://github.com/WurstPlus/wurst-plus-three/files/6524072/latest.log)

**Comment by mememememememeWEEE** [comment]
here's the crash report

**Comment by RealzPrestige** [comment]
u use predict place??

**Comment by mememememememeWEEE** [comment]
idk what it does
first time using W+3, it's not in any other pvp cleints

**Comment by RealzPrestige** [comment]
> idk what it does
> first time using W+3, it's not in any other pvp cleints

Can u send me ur ca config? my discord is ! zPrestige_#6625

**Comment by TediousDuskFall** [comment]
t u r n  o f f  p r e d i c t  p l a c e
