### ISSUE TITLE
offhand kinda shit

### ISSUE THREAD

**Issue by Gaamr** [WurstPlus/wurst-plus-three#137]
theres a huge delay between totems when im in pvp i pop once and ive died because of it so many times

turn on offhand
pop a totem (preferably with crystals)
see how long it takes

it took ~2-3 seconds for another totem to be put in my offhand but it varies a lot and can be simulated with freecam

**Comment by wallhacks0** [comment]
offhand will be different next update

**Comment by Gaamr** [comment]
sick thanks
