### ISSUE TITLE
[BUG] The terrain check in crystalaura rigs the damage calculations and leads to wrong damage calculated

### ISSUE THREAD

**Issue by CandyCat1029** [WurstPlus/wurst-plus-three#150]
public static float getBlockDensity3(Vec3d vec, AxisAlignedBB bb, World world) {
        double d0 = 1.0D / ((bb.maxX - bb.minX) * 2.0D + 1.0D);
        double d1 = 1.0D / ((bb.maxY - bb.minY) * 2.0D + 1.0D);
        double d2 = 1.0D / ((bb.maxZ - bb.minZ) * 2.0D + 1.0D);
        double d3 = (1.0D - Math.floor(1.0D / d0) * d0) / 2.0D;
        double d4 = (1.0D - Math.floor(1.0D / d2) * d2) / 2.0D;

        if (d0 >= 0.0D && d1 >= 0.0D && d2 >= 0.0D)
        {
            int j2 = 0;
            int k2 = 0;

            for (float f = 0.0F; f <= 1.0F; f = (float)((double)f + d0))
            {
                for (float f1 = 0.0F; f1 <= 1.0F; f1 = (float)((double)f1 + d1))
                {
                    for (float f2 = 0.0F; f2 <= 1.0F; f2 = (float)((double)f2 + d2))
                    {
                        double d5 = bb.minX + (bb.maxX - bb.minX) * (double)f;
                        double d6 = bb.minY + (bb.maxY - bb.minY) * (double)f1;
                        double d7 = bb.minZ + (bb.maxZ - bb.minZ) * (double)f2;

                        if (world.rayTraceBlocks(new Vec3d(d5 + d3, d6, d7 + d4), vec) == null && world.rayTraceBlocks(new Vec3d(d5 + d3, d6, d7 + d4), vec).typeOfHit == RayTraceResult.Type.BLOCK && thatBlockArrayVariable.contains(mc.world.getBlockState(world.rayTraceBlocks(new Vec3d(d5 + d3, d6, d7 + d4), vec).getBlockPos()).getBlock()))
                        {
                            ++j2;
                        }

                        ++k2;
                    }
                }
            }

            return (float)j2 / (float)k2;
        }
        else
        {
            return 0.0F;
        }
    }
this should work

**Comment by TrvsF** [comment]
can you make this a pull request please? if not I'll have a look when i have more time

**Comment by CandyCat1029** [comment]
maybe i'll make a pr tomorrow
