### ISSUE TITLE
auto32k dispenser

### ISSUE THREAD

**Issue by Trixskee** [WurstPlus/wurst-plus-three#152]
Travis added an auto32k module on w+2 but it would fail most of the time and I play on a server called impurity.me (a 32k meta server) so i was wondering if you could add the w+2 one but tweak it so you can 32k people. (dispenser 32k not hopper)

**Comment by TheLLaw** [comment]
why do you need that lmao 32ks are ded

**Comment by TheLLaw** [comment]
the server is also ded

**Comment by wallhacks0** [comment]
done
