### ISSUE TITLE
Make GUI scrollable

### ISSUE THREAD

**Issue by wijiler** [WurstPlus/wurst-plus-three#153]
I hate it when I’m trying to config something in w+3 and I can’t see it even when I’m on the smallest GUI scale

It would be nice if you could implement this in the GUI

**Comment by wallhacks0** [comment]
if you take your mouse weel and scroll it the location of the clickgui will change

**Comment by Drakesdrs** [comment]
Make a screen and container for clickgui

**Comment by TediousDuskFall** [comment]
the thing in between your right mouse key and your left mouse key, that little bumpy thing
