### ISSUE TITLE
Ca lag.

### ISSUE THREAD

**Issue by RealzPrestige** [WurstPlus/wurst-plus-three#155]
When ur playing like cc theres like 30 ppl at ffa and then when u turn on ca it calculates for all 30 people ( i think ) cuz when its a fair 1v1 i dont lag at all. Make it so it only calculates people in target range.

**Comment by Madmegsox1** [comment]
maybe we should use threading @TrvsF

**Comment by Madmegsox1** [comment]
@RealzPrestige  test this out and lemme know if it fixes it
