### ISSUE TITLE
[SUGGESTION] BedAura

### ISSUE THREAD

**Issue by Doogie13** [WurstPlus/wurst-plus-three#156]
**Is your feature request related to a problem? Please describe.**
w+2 wont work for me and its BA is good apparently (im not asking for support with that its discontinued)

**Describe the solution you'd like**
Either a port of w+2 BA or something new designed for 1.12.2 servers like 5b not yet another ecme BA.

**Describe alternatives you've considered**
suicide

**Additional context**
https://www.youtube.com/watch?v=BH-uxkwoLBk

**Comment by CandyCat1029** [comment]
https://github.com/CandyCat1029/BedAura/blob/main/BedAura.java
@TrvsF  u can paste this.
It's pretty chinese but at least it works

**Comment by Doogie13** [comment]
> https://github.com/CandyCat1029/BedAura/blob/main/BedAura.java
> @TrvsF u can paste this.
> It's pretty chinese but at least it works

would it not be better for you to make a PR with it yourself so it doesn't look like skidding?
