### ISSUE TITLE
[BUG] ca weird prioritization

### ISSUE THREAD

**Issue by TediousDuskFall** [WurstPlus/wurst-plus-three#158]
ca always places according to min dmg and not the maximum possible dmg, eg if you city boss someone it wont place crystals where it would do the most damage but instead place it where it aligns with the min dmg requirement (mine is literally 5), so im missing out on lots of kills :(

**Comment by TediousDuskFall** [comment]
*it prioritizes min dmg over max possible dmg

**Comment by wallhacks0** [comment]
you are using mode range so it will take the closest crystal that deals the min damage. making this issue a special issue!

**Comment by TediousDuskFall** [comment]
> you are using mode range so it will take the closest crystal that deals the min damage. making this issue a special issue!

wtf is mode range
