### ISSUE TITLE
[SUGGESTION] Place obbi if no valid spots to crystal like salhack (will be useful in terrain pvp)

### ISSUE THREAD

**Issue by papahappa** [WurstPlus/wurst-plus-three#159]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RealzPrestige** [comment]
terrain pvp imagine :)

**Comment by Madmegsox1** [comment]
@papahappa  we have done this in version 0.6.0
