### ISSUE TITLE
ca doing monkey #2[BUG]

### ISSUE THREAD

**Issue by TediousDuskFall** [WurstPlus/wurst-plus-three#164]
hi. please dont close this ticket with "fixed in 0.6" like last time, because im using 0.6 :(

https://streamable.com/8h3iuj - uscpvp 
https://streamable.com/couwma - 0b

**Comment by RealzPrestige** [comment]
0b is horrible stop cry now

**Comment by RealzPrestige** [comment]
config issue yes

**Comment by SWP360** [comment]
config issue.

**Comment by TediousDuskFall** [comment]
yes i changed my wall range to 6 thanks friends
