### ISSUE TITLE
a few bugs[BUG]

### ISSUE THREAD

**Issue by TediousDuskFall** [WurstPlus/wurst-plus-three#165]
keypearl crashes game/kicks you from server if pearls arent in your hotbar
ca shouldnt be rendering/attempting to place when there are no crystals in your offhand or mainhand
add settings for hotbar replenish (delay, threshold, crystals/food/exp etc.)
no fp sword completely stops ca, not just faceplace. conflicts with antiweakness.

all of these bugs are from 0.6

**Comment by Gaamr** [comment]
0.6 is out?

**Comment by wallhacks0** [comment]
the ca is not attempting to place when no crystals in hotbar i fixed that already
the rest of your issues sound really bad tho thanks for reporting

**Comment by TrvsF** [comment]
rest have been fixed
