### ISSUE TITLE
[BUG] Kick for crystalpvp.cc and us.crystalpvp.cc

### ISSUE THREAD

**Issue by Madmegsox1** [WurstPlus/wurst-plus-three#166]
**Describe the bug**
java.util.ConcurrentModificationException in EventProcessor.postEvent(EventProcessor.java:61) but only cause by packet_handler
This then Triggers a java.lang.NullPointerException in EntityRenderer:handler$getMouseOverHook$zzh000:3265, Note this only happens on crystalpvp.cc 

**To Reproduce**
Play crystalpvp.cc 

[crash.txt](https://github.com/WurstPlus/wurst-plus-three/files/6634502/crash.txt)

**Comment by TrvsF** [comment]
couldnt u just do something like this
public final boolean postEvent(@NotNull Event event) {
        List<Listener> eventClone = new ArrayList<>(events);
        eventClone.spliterator().forEachRemaining(listener -> {
            if(listener != null && listener.event != null && listener.event == event.getClass()){
                listener.method.setAccessible(true);
                try {
                    listener.method.invoke(listener.object, event);
                } catch (IllegalAccessException | InvocationTargetException e) {
                    e.printStackTrace();
                }
            }
        });
        events = eventClone;
        return true;
    }

**Comment by RealzPrestige** [comment]
skill issue 🤦🏿‍♂️

**Comment by Madmegsox1** [comment]
fixed i think

**Comment by 3x11** [comment]
> fixed i think

no it stills kicks
