### ISSUE TITLE
speedmine render[BUG]

### ISSUE THREAD

**Issue by TediousDuskFall** [WurstPlus/wurst-plus-three#169]
speedmine render seems delayed for some reason im using default config 

usually, when you're done mining it should turn green within a second but you have to wait around five for the render to turn green, very misleading also easily desyncs with the block you're actually mining and the block thats still being rendered

block stops getting rendered when you're around 4 blocks away, doesnt matter what your range is set to

**Comment by wallhacks0** [comment]
We should probably make some reset option that resets when out if range or if the player started hitting another block

**Comment by Madmegsox1** [comment]
Ye super easy fix I use server ticks instead of client ticks for counting the time

**Comment by TrvsF** [comment]
@Madmegsox1 fix it then
