### ISSUE TITLE
[BUG]different modes

### ISSUE THREAD

**Issue by TediousDuskFall** [WurstPlus/wurst-plus-three#170]
render in crystal aura is set to pretty at default but once you switch modes it dissapears
the same goes for speed, mode is at strafe on default but once you switch it, you will only see yport and fake

**Comment by wallhacks0** [comment]
could you make a video of this problem?

**Comment by TrvsF** [comment]
> 
> 
> could you make a video of this problem?

i just tried it, its a thing (for some reason), ill fix it now
