### ISSUE TITLE
autoclip

### ISSUE THREAD

**Issue by guntahBruh** [WurstPlus/wurst-plus-three#171]
where do i find the clips

**Comment by RealzPrestige** [comment]
Oml most retarded question ive ever seen

**Comment by TediousDuskFall** [comment]
> Oml most retarded question ive ever seen
you would rather call him a retard than actually save everyone time and answer the question :(

**Comment by RealzPrestige** [comment]
> > Oml most retarded question ive ever seen
> > you would rather call him a retard than actually save everyone time and answer the question :(

ok ill answer. youre supposed to have a clipping software like Medal or anything which has a keybind to save a clip. Wp3 doesnt have a built in clipping software so you have to bind it to what clipping for for example medal is bound to. Say to make a clip in Medal you press F8, then your autoclip bind is F8. congrats
