### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by ghost** [WurstPlus/wurst-plus-three#172]
fall height for offhand
build height interact
esp more modes (storage animals etc)
a spammer
custom autoez

**Comment by TediousDuskFall** [comment]
or you could make a “totem when missing armor piece”

**Comment by wallhacks0** [comment]
I am working on totem when 32k and on a fall damage check

**Comment by Teddyymc** [comment]
And maybe a key for gap swap and/or totem swap
