### ISSUE TITLE
[BUG] Cannot load the project in Intellij IDEA

### ISSUE THREAD

**Issue by chocopie69** [WurstPlus/wurst-plus-three#175]
When I try to load the project in Intellij, it has some weird errors, I tried everything but it still doesn't work

Here are some error screenshots:
![idea64_yGEPK8jlJs](https://user-images.githubusercontent.com/64907181/122061102-6856fb80-ce18-11eb-992b-dc9c4160e82b.png)
![idea64_q18c4fuQgk](https://user-images.githubusercontent.com/64907181/122061133-6e4cdc80-ce18-11eb-9671-a09777073c85.png)
![idea64_2D4JIM03EN](https://user-images.githubusercontent.com/64907181/122061145-7147cd00-ce18-11eb-8723-d2104a59bd34.png)
![idea64_2VNLyleJdp](https://user-images.githubusercontent.com/64907181/122061160-73aa2700-ce18-11eb-9283-1d53df57ccf6.png)

My discord is retxrd#8543

**Comment by wallhacks0** [comment]
setup

**Comment by wallhacks0** [comment]
decomp

**Comment by wallhacks0** [comment]
workspace

**Comment by wallhacks0** [comment]
then try and rebuild the gradle

**Comment by chocopie69** [comment]
I can setup decomp workspace / build the project through command prompt, but I can't do shit in intellij

**Comment by wallhacks0** [comment]
does setup decomp work space throw an error if run in intelij?

**Comment by chocopie69** [comment]
Ok I fixed the problem, I setup decomp workspace by command prompt, then load the project in Intellij, it works now.
