### ISSUE TITLE
step no work[BUG]

### ISSUE THREAD

**Issue by WebFag** [WurstPlus/wurst-plus-three#177]
**Describe the bug**
basiclly i tried vanilla step and it does nothing, i tried normal step and still doesnt work
**To Reproduce**
1. Turn on module: '...'
2. Set the setting to '....'
3. See error

**Expected behavior**
step does nothing

**Screenshots**
Add screenshots or videos to help explain the problem.

**Additional context**

**Comment by TrvsF** [comment]
what server? what mode? what other clients are you using?

**Comment by WebFag** [comment]
i have tried it on cc and i am on vanilla mode, i am using it with pyro and gamesense

**Comment by WebFag** [comment]
turns out w+3 has issues when used with pyro, its step wont work and its nametags and possibly more things wont work, i tried removing pyro and everything was fixed

**Comment by WebFag** [comment]
can u fix this?

**Comment by Madmegsox1** [comment]
Why are you using pyro

**Comment by WebFag** [comment]
anchor

**Comment by WebFag** [comment]
and packetfly
