### ISSUE TITLE
[BUG] drawn, compatibility etc.

### ISSUE THREAD

**Issue by ghost** [WurstPlus/wurst-plus-three#183]
some modules cannot be accessed through commands since they have a space in them (eg. Fake Player, Void ESP etc.)

Rename  “shown” to “notify” (it’s misleading) and add a “drawn” option to modules.

Fix compatibility - client doesn’t work with a lot of other clients/some modules won’t work when you run other other clients

Add “anti naked” to ca

**Comment by Madmegsox1** [comment]
Use a under score

**Comment by TediousDuskFall** [comment]
primarily konas

**Comment by wallhacks0** [comment]
FUCK COMPAT W+3 on tope
