### ISSUE TITLE
[BUG] Cape not being loaded 

### ISSUE THREAD

**Issue by Furiouskid242343432423** [WurstPlus/wurst-plus-three#184]
**Describe the bug**
So first off i was not able to log into my discord account for about 4-5 hours so i just created a new account and while i created the account i got the free nitro and boosted the server 2 times, after i boosted the server 2 times i pinged travis and also typing my mc username in (furiouskid8) after i did that a day or 2 later i ask if i can still get the cape because on my alt account i boosted 2 times, he says yes and he said he did everyones cape from above. After that I boot up mc enable capes on wurstplus3 0.6.2 and rusherhack and yet my cape isnt there, after i realized that i opened my mods folder opened wurstplus3 folder opened the capes folder and its empty. not sure what happend and if i did anything wrong or missed anything? if i did miss something feel free to call me brainlet lol

**Screenshots**
![image](https://user-images.githubusercontent.com/83801755/122594252-cc560b80-d034-11eb-9370-d5c6d9e67ab3.png) this is where i boosted the server 2 times
![image](https://user-images.githubusercontent.com/83801755/122594294-da0b9100-d034-11eb-8691-190e951a6c11.png)
 he replys saying yes and does everyones cape 
 
![image](https://user-images.githubusercontent.com/83801755/122594382-f0195180-d034-11eb-9d47-5604292cf101.png)
 nothing appears in the cape folder
![image](https://user-images.githubusercontent.com/83801755/122594406-f7d8f600-d034-11eb-81c5-4c77d5b6ec1e.png)
when i enabled cosmentics and restarted my game like 10 times. 
ltm what i did wrong and or call me brainlet out of  ur enjoyment lol

**Comment by Furiouskid242343432423** [comment]
oh and i do own the optifine cape (bought it 2 days ago)

**Comment by Furiouskid242343432423** [comment]
![image](https://user-images.githubusercontent.com/83801755/122595357-55217700-d036-11eb-83ca-449fe67915ed.png)

**Comment by Madmegsox1** [comment]
No the capes folder are for custom capes what is Ur Minecraft uuid

**Comment by Furiouskid242343432423** [comment]
should i dm it to you on discord or post it here?
