### ISSUE TITLE
[BUG] HoleFill working strangely

### ISSUE THREAD

**Issue by CandyCat1029** [WurstPlus/wurst-plus-three#186]
**Describe the bug**

**To Reproduce**
use fakeplayer
toggle holefill
delete urself friend

**Expected behavior**
holefill the holes around the fakeplayer

**Screenshots**
https://cdn.discordapp.com/attachments/762343301822545971/855771733642182686/Wurst3___v0.6.1_2021-06-19_19-30-06.mp4

**Comment by RealzPrestige** [comment]
You Congruity failed to align Exhort Ephemeral Bisector of the HoleFill, this means that you'll have to Laconize the Munificent Setting in the Module to align the Zephyr too to make it work.

**Comment by wallhacks0** [comment]
@RealzPrestige couldn't have said it any better myself!
