### ISSUE TITLE
[BUG] when trying to configure settings (for example and what was most prominent for me, viewmodel) its hard to get the values right and i have to click away just to drag it

### ISSUE THREAD

**Issue by Gaamr** [WurstPlus/wurst-plus-three#187]
**Describe the bug**
dragging settings in gui is buggy

**To Reproduce**
1 open gui
2 go to a module that has a draggable option (viewmodel for me)
3 try and drag near the value

**Expected behavior**
it shouldn't work and to actually change it you have to click in a gray area or farther away from it

**Comment by Gaamr** [comment]
not a high priority thing and not game breaking but it gets really annoying

**Comment by TediousDuskFall** [comment]
to add to this, the gui still does this stupid thing where if you have one section overlaying the other then they both get dragged around.

**Comment by wallhacks0** [comment]
thats perfectly acceptable behaviour almost all clients have this?

**Comment by FSNCryo** [comment]
I cannot play four seasons, I would like to have timestamps for each season please.
