### ISSUE TITLE
ca silentswitch

### ISSUE THREAD

**Issue by RealzPrestige** [WurstPlus/wurst-plus-three#198]
ok

**Comment by Madmegsox1** [comment]
bruh

**Comment by TrvsF** [comment]
after looking at other people's implimentation it seems like all it does is send a fuck tonne of packets to the server and makes the ca a little slower because youre not using offhand. Unless a good reason is given Im not gonna add it

**Comment by BurrowIsPoggers** [comment]
you should prob add it because u can aggro more and not worry about offhand failing

**Comment by amongusenjoyer69** [comment]
it only works on servers like cc, literally no point.

**Comment by wallhacks0** [comment]
offhand failing is config issue and desync is worse then a potential offhand fail
