### ISSUE TITLE
[SUGGESTION] voidesp

### ISSUE THREAD

**Issue by ghost** [WurstPlus/wurst-plus-three#200]
voids could be detected not through player y level but instead by how many blocks are on top of it (0 meaning only when exposed).

**Comment by TediousDuskFall** [comment]
this way my voidesp can stop rendering voids that were exposed when chunks were loading/after i covered them up + become less intrusive

**Comment by TrvsF** [comment]
but then you'd be unaware if your stood on a block that has a void under it and someone could mine you from underneath?

**Comment by TediousDuskFall** [comment]
> but then you'd be unaware if your stood on a block that has a void under it and someone could mine you from underneath?

if u had ur voidesp on 1 then it will detect voids that are covered by 1 block, so you would be fine

**Comment by wallhacks0** [comment]
we check if the block above is bedrock or not. or would this make it still render while chunks are loading in?

**Comment by TediousDuskFall** [comment]
but then what about higher bedrock blocks

**Comment by wallhacks0** [comment]
idk what if you make the thing and make a pull request to show us?

**Comment by TediousDuskFall** [comment]
just make it so that it doesnt render once the void is covered with a certain amount of blocks, its just really annoying when you pearl away and for the brief second the chunks are loading the voids are rendered and then when the chunks are loaded you have this massive spot of white underneath you from the voidesp.

**Comment by TediousDuskFall** [comment]
> we check if the block above is bedrock or not. or would this make it still render while chunks are loading in?

the bedrock doesnt load until the chunks are too i think so it'll still expose the void and get rendered
