### ISSUE TITLE
[SUGGESTION] crystalaura

### ISSUE THREAD

**Issue by TediousDuskFall** [WurstPlus/wurst-plus-three#201]
this may sound like complete nonsense/a dumb idea but hear me out

an antistuck mode for the ca, this basically places a crystal elsewhere that might not match min enemy place+break but will align with max self dmg. basically when your ca gets stuck because its trying to place right next to an already placed crystal, it will recognize what is going on and place+blow up a crystal nearby to break the crystal that is preventing it from placing, thus allowing the ca to work properly again! :) you could add a delay to when it recognizes the desync, so that this doesnt affect the crystalaura when chasing an enemy

perhaps this can replace chain mode?

**Comment by wallhacks0** [comment]
this would cause more rotations wich will cause more desync wich will cause more problems. buut i have an idea to still make it easy to so il test it.

**Comment by zihasz** [comment]
> this would cause more rotations wich will cause more desync
@wallhacks0 this shouldn't happen if you spoof rotations, if you don't then that's a serious issue
