### ISSUE TITLE
[BUG] Burrow

### ISSUE THREAD

**Issue by DriftyDev** [WurstPlus/wurst-plus-three#204]
**Describe the bug**
When reverse step is enabled if you enable burrow, burrow won't work

**To Reproduce**
1. Enable reverse step
2. Enable burrow
3. Burrow doesn't work

**Expected behavior**
Burrow to work.

**Solutions**
Auto disable reverse step when burrow is enabled, when you are burrowed then, re-eanble reverse step

**Comment by WMSGaming** [comment]
> **Describe the bug**
> When reverse step is enabled if you enable burrow, burrow won't work
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Enable reverse step
> 2. Enable burrow
> 3. Burrow doesn't work
> 
> **Expected behavior**
> Burrow to work.
> 
> **Solutions**
> Auto disable reverse step when burrow is enabled, when you are burrowed then, re-eanble reverse step

config issue

**Comment by RealzPrestige** [comment]
Config issue

**Comment by amongusenjoyer69** [comment]
skill issue

**Comment by Madmegsox1** [comment]
works for me so im not sure why
