### ISSUE TITLE
[BUG] Killaura sort

### ISSUE THREAD

**Issue by chocopie69** [WurstPlus/wurst-plus-three#205]
Codes issue bruh

https://github.com/WurstPlus/wurst-plus-three/blob/0.7.0/src/main/java/me/travis/wurstplusthree/hack/hacks/combat/KillAura.java

![chrome_zuyHeTJLZu](https://user-images.githubusercontent.com/64907181/123550707-080d7580-d799-11eb-8971-95c8d4231c39.png)

it should be:
```
if (this.targetMode.is("Closest") && mc.player.getDistanceSq(entity) < distance) {
    target = entity;
    distance = mc.player.getDistanceSq(entity);
}
if (this.targetMode.is("Health") && ((double) EntityUtil.getHealth(entity) < maxHealth)) {
    target = entity;
    maxHealth = EntityUtil.getHealth(entity);
}
```

op client!!!

edit: changed other shit

**Comment by wallhacks0** [comment]
make pr

**Comment by amongusenjoyer69** [comment]
skill issue

**Comment by Madmegsox1** [comment]
please make a pr
