### ISSUE TITLE
[SUGGESTION] so i use wp3 alot so i was going to recommend a target hud like the one in game sense bit less chinese hud module :)

### ISSUE THREAD

**Issue by priseore** [WurstPlus/wurst-plus-three#206]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wallhacks0** [comment]
congrats you described the complete issue in the title

**Comment by chocopie69** [comment]
"bit less chinese"
best idea ever

**Comment by RealzPrestige** [comment]
Webhack has targethud 😎
