### ISSUE TITLE
[BUG] Fly activation when CA is on 

### ISSUE THREAD

**Issue by thebruhmoment** [WurstPlus/wurst-plus-three#208]
**Describe the bug**
like, when i toggle CA it seems like enabling fly , i cant move normally 

**To Reproduce**
1. Turn on module: CA
2. Set the setting to https://u-got-ip-logged-by-the.club/7366f42beac9e06f8.mp4
3. See 

**Expected behavior**
expected to place and brake crystals you know, not flying ( also i tested in suvival without AC and it flies like crazy , brakes int value and crashes the whole instance in mc so i cant open it again )

**Screenshots**
https://youtu.be/at07mRAKYOE

**Additional context**
pls fix or tell me that im dumb and thats {modulename} causing it

**Comment by TediousDuskFall** [comment]
Turn off Threaded you monkey

**Comment by thebruhmoment** [comment]
> Turn off Threaded you monkey

it was entity predict
