### ISSUE TITLE
bruh[SUGGESTION]

### ISSUE THREAD

**Issue by amongusenjoyer69** [WurstPlus/wurst-plus-three#210]
what I meant in my last issue is that you should add a max self break and a max self place, this way the ca won’t desync if you suddenly move in front of it and when you’re chasing someone it will place and destroy the maximum damage to your opponent 👍 💯 👍 (if you config it right)

**Comment by amongusenjoyer69** [comment]
like Phobos

**Comment by wallhacks0** [comment]
this is a cool idea but it works out bad in practice. This would create more bloat. Could you describe why you want this?

**Comment by chocopie69** [comment]
among us??? imposter????? venting in minecraft????

**Comment by TrvsF** [comment]
> this is a cool idea but it works out bad in practice. This would create more bloat. Could you describe why you want this?

He just did, ill add it

**Comment by wallhacks0** [comment]
OK but please use the already used settings we already have just add a check in the code, having a different break min damage then a place min damage is useless in my  opinion

**Comment by TediousDuskFall** [comment]
it’s not useless oh my god! ok 👎 👎 👎 you can even do this on fake player and see for yourself bruh! ‘!!: let’s say you are crystaling then you move forward slightly, the ca will place behind the block it was targeting causing a desync and a freezing in the ca becaause as we all know you CANT :🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫 put a CRYSTAL NEXT TO A CRYSTAL! if we had MAX SELF BREAK DMG however, THIS WOULD BREAK THE CRYSTAL (IF YOUR MAX SELF DMG WAS HIGH ENOUGH) REMOVJNG THE DESYNC AND THEN HAPPILY ALLOWING YOUR CA TO CONTINUE PLACING! IN CHASING IF YOU HAVE LIKE 5 MAX SELF DMG HOW ARE YOU GOING TO CHASE?!! WITH WP3 CA YOU ARE FORCED TO SET IT AT 8+ USUALLY DOING MORE DAMAGE TO YOURSELF! THIS DESYNCS LIKE EVERYTIME YOU CHASE SOMEONE AND IF YOU HAVE SOUND ON YOU CAN HEAR ONLY 2 OR 3 CRYSTALE ARE BEING BROKEN, THANKS.

**Comment by amongusenjoyer69** [comment]
> > this is a cool idea but it works out bad in practice. This would create more bloat. Could you describe why you want this?
> 
> He just did, ill add it

thanks yes I appreciate you

**Comment by wallhacks0** [comment]
it will just break the crystal, having different damage checks wont change that

**Comment by TediousDuskFall** [comment]
> it will just break the crystal, having different damage checks wont change that

no the point of max self dmg is it wil break the crystal desyncing you over max self place dmg, let’s say ur max self dmg is 10 well when the crystal is doing 11dmg it has to place backwards by 1 block to keep it at 10, this then creates a desync, the ca keeps trying to place but you can’t place 2 crystals next to each other. It can’t break the crystal in front of the one that’s preventing it from placing because it does 11 dmg not 10 (Or at least that’s why I think he wants it added)

**Comment by TediousDuskFall** [comment]
so if you had your max self break dmg at 12 for example and your max place dmg at 10, when this type of situation occurs (which is extremely common) it will break the crystal causing the desync and continue placing

**Comment by TediousDuskFall** [comment]
this is sort of difficult to replicate with a fake player but against a real one when they’re moving you see it happening all the time

**Comment by amongusenjoyer69** [comment]
exactly...

**Comment by wallhacks0** [comment]
the ca currently just breaks the crystal that deals the most damage, so this problem shouldnt happen in the first place

**Comment by amongusenjoyer69** [comment]
since you don’t understand I will clip a video for you, give me a moment.

**Comment by amongusenjoyer69** [comment]
https://user-images.githubusercontent.com/86632988/123809302-7c423900-d8bf-11eb-8b60-3fd3199c4688.mp4

**Comment by wallhacks0** [comment]
put down range xD

**Comment by amongusenjoyer69** [comment]
Uploading Wurst+3 _ v0.7.0 2021-06-29 10-00-42_Trim.mp4…

**Comment by amongusenjoyer69** [comment]
https://user-images.githubusercontent.com/86632988/123811572-5b7ae300-d8c1-11eb-9bbb-352727be9956.mp4

**Comment by amongusenjoyer69** [comment]
turned on debug so you could see what the ca was trying to do

**Comment by wallhacks0** [comment]
you are trying to place from a really far range thats why its not working, adding different damage checks wont fix this

**Comment by amongusenjoyer69** [comment]
> you are trying to place from a really far range thats why its not working, adding different damage checks wont fix this

what the ca debug never tries to break the crystal in front lol this is not a range issue

**Comment by amongusenjoyer69** [comment]
it places fine after i shoot the crystal with a bow

**Comment by wallhacks0** [comment]
thats really weird let me look in to that

**Comment by amongusenjoyer69** [comment]
> thats really weird let me look in to that

yeah, it wouldnt make sense if the ca isnt able to break the crystal infront of it (5 blocks) yet able to break the crystal behind it (5.5 blocks)

**Comment by wallhacks0** [comment]
I think its because of you moving in front of the crystal, this will make it hit maxselfdamage and thereby ignore the crystal, to fix this try lower your mindamage

**Comment by amongusenjoyer69** [comment]
this is literally what ive been trying to say, it's surpassing the max self damage so it neglects the crystal and places closely behind it, to stop this you add a max self break so it breaks the crystal in front. with a moving target its even worse. my min enemy place could be 2 and it would still be placing that far there since the ca is supposed to be placing where the crystals are doing the maximum damage to your opponent

**Comment by wallhacks0** [comment]
I hate to give it buy you got a point Il add this after I clean up ca settings

**Comment by amongusenjoyer69** [comment]
thanks, you understand and thats all that matters 👍

**Comment by wallhacks0** [comment]
after having thought about it I think im making something that will turn on special entitycheck after it has been stuck for some more then 5 ticks

**Comment by wallhacks0** [comment]
done fixed it ca now never gets stuck at all and I didnt add minbreakdamage (:<

**Comment by amongusenjoyer69** [comment]
good job thanks 🙏🙏 

well you good morning ☀️😃😃🌞 day I was really like an old one ☝️ this year I am in the top half who made it a great 👍 was a fun night of fun to watch it for a long while lol 😝 has been the most interesting 

okay type suggestions are weird
