### ISSUE TITLE
radio [SUGGESTION]

### ISSUE THREAD

**Issue by 1Lunarist** [WurstPlus/wurst-plus-three#212]
add more songs to the radio feature that aren't by pitbull, or just let users add midi/mp3 files so they can play whatever songs they want ¯\_(ツ)_/¯

**Comment by TediousDuskFall** [comment]
but I love pit bull ur weird

**Comment by 1Lunarist** [comment]
> but I love pit bull ur weird

i like pitbull but im tired of hearing his sexy voice every single time i open minecraft

**Comment by amongusenjoyer69** [comment]
> > but I love pit bull ur weird
> 
> i like pitbull but im tired of hearing his sexy voice every single time i open minecraft

skill issue

**Comment by 1Lunarist** [comment]
> > > but I love pit bull ur weird
> > 
> > 
> > i like pitbull but im tired of hearing his sexy voice every single time i open minecraft
> 
> skill issue

how is that a fucking skill issue

**Comment by 1Lunarist** [comment]
shut the fuck up cyka

**Comment by amongusenjoyer69** [comment]
who’s cyka?

**Comment by 1Lunarist** [comment]
you are cyka

**Comment by amongusenjoyer69** [comment]
wow, now that’s just rude. you are so immature and not charming at all.

**Comment by wallhacks0** [comment]
this isnt about the actual suggestion anymore, And I think travis doesnt agree anyway
