### ISSUE TITLE
what[BUG]

### ISSUE THREAD

**Issue by amongusenjoyer69** [WurstPlus/wurst-plus-three#213]
ca min enemy break doesnt account for friends 

if you manually place a crystal and your friend is next to it they will die

**Comment by wallhacks0** [comment]
we have no min break in the ca so no shit it doesnt account for friends

**Comment by wallhacks0** [comment]
nvm we do have that

**Comment by amongusenjoyer69** [comment]
i laughed

**Comment by chocopie69** [comment]
i laughed

**Comment by amongusenjoyer69** [comment]
stop this

**Comment by wallhacks0** [comment]
will fix but im closing the issue for now
