### ISSUE TITLE
why[BUG]

### ISSUE THREAD

**Issue by amongusenjoyer69** [WurstPlus/wurst-plus-three#214]
trying not to be annoying. 

like half of the modules in offhand don’t work/have no purpose/incomprehensible 

who made this what are you doing

**Comment by chocopie69** [comment]
config issue

**Comment by amongusenjoyer69** [comment]
I’m literally going to blow up.

**Comment by chocopie69** [comment]
imposter from among us?

**Comment by wallhacks0** [comment]
its sometimes annoying to config but it does work

**Comment by amongusenjoyer69** [comment]
Things like “crystal check” for example physically don’t work
