### ISSUE TITLE
[SUGGESTION] nullcheck codes in Hack.java instead of in every module class

### ISSUE THREAD

**Issue by chocopie69** [WurstPlus/wurst-plus-three#219]
why r u adding nullcheck in every single shit, since every modules extends Hack.java, you can just add null checks in it, it will check null shit in all modules so you don't have to go to every single class and add null checks

**Comment by wallhacks0** [comment]
Some modules have to be checked om different things.

**Comment by amongusenjoyer69** [comment]
cocolapte pie

**Comment by chocopie69** [comment]
stfu

**Comment by linustouchtips** [comment]
true, why are you guys doing this lmao

**Comment by wallhacks0** [comment]
some modules ehh dont need a nullcheck

**Comment by linustouchtips** [comment]
then just use the event for it, you almost always need a null check on the methods from your module class
