### ISSUE TITLE
[SUGGESTION]Crystal Tracking

### ISSUE THREAD

**Issue by wallhacks0** [WurstPlus/wurst-plus-three#221]
Im being such a big brain rn this will improve speed like crazy.

**Comment by chocopie69** [comment]
what is crystal tracking tho

**Comment by amongusenjoyer69** [comment]
wallhacks put speed aside for now the ca is an absolute nightmare on strict and semi strict servers regardless of your config you have to fix that first

**Comment by wallhacks0** [comment]
trvsf was making yawstep not me

**Comment by chocopie69** [comment]
can someone answer me what is crystal tracking

**Comment by wallhacks0** [comment]
nvm fixed it in another way
