### ISSUE TITLE
[BUG] holefill toggle doesnt work if entity is in hole

### ISSUE THREAD

**Issue by iTwisten** [WurstPlus/wurst-plus-three#223]
**Describe the bug**
if you turn on holefill toggle currently it does not work because hole with player still counts as a empty whole. only works if you and enemy jump out of hole.

**To Reproduce**
1. Turn on module: 'holefill'
2. Set the setting to 'toggle on'
3. See error

**Expected behavior**
holefill to ignore holes with players in and toggle off

**Screenshots**
no
**Additional context**
no

**Comment by amongusenjoyer69** [comment]
skill issue

**Comment by Teddyymc** [comment]
No. real issue also put it in my bug/suggestion request

**Comment by amongusenjoyer69** [comment]
I’m joking lol

**Comment by Teddyymc** [comment]
I'm not.

**Comment by Pexku789** [comment]
User issue

**Comment by Madmegsox1** [comment]
Strange as this doesn't happen to me

**Comment by Teddyymc** [comment]
I have the same issue
