### ISSUE TITLE
[BUG] [SUGGESTION]

### ISSUE THREAD

**Issue by amongusenjoyer69** [WurstPlus/wurst-plus-three#224]
max self break dmg and max enemy break dmg only apply to the targeted block not for all crystals making them useless. 

holehp is a nightmare 

predict block does nothing but dc me

ca is a disaster on semi and strict servers regardless of config

offhand needs fallcheck totem on ely

add build height

make velocity and noslow separate modules, fix compatibility with them too

threaded in ca crashes game and fucks movement

hole fill I don’t need to explain

name tags need fill color option as well

nametags explode your game on servers like 9b

speed mine renders crazy shit when you mine a slab or anything that isn’t a block

wtf is silent switch bound to a key make it automatic

other than that client is pretty sick great job devs!!,11!1

**Comment by wallhacks0** [comment]
this is not true, and keep the rest of your issues separate please

**Comment by amongusenjoyer69** [comment]
what’s not true

**Comment by amongusenjoyer69** [comment]
reopen this issue immediately

**Comment by wallhacks0** [comment]
no make separate issues for better tracking

**Comment by amongusenjoyer69** [comment]
what’s hit true

**Comment by wallhacks0** [comment]
and if you would look at the code you would see that all checks are applied to all positions before deciding which position to break/place

**Comment by amongusenjoyer69** [comment]
I’m not going to make 100 separate issues for each bug, why did you close this

**Comment by amongusenjoyer69** [comment]
> and if you would look at the code you would see that all checks are applied to all positions before deciding which position to break/place

i swear to god dude

**Comment by wallhacks0** [comment]
you can swear to god but it wont change how our code works

**Comment by amongusenjoyer69** [comment]
no like okay but your code isn’t working?!1a?1!!11a

**Comment by wallhacks0** [comment]
its not mine and it seems to work great now go open multiple issues for multiple different problems

**Comment by amongusenjoyer69** [comment]
okay max self break dmg only works for the targeted block


sorry

**Comment by amongusenjoyer69** [comment]
min enemy break is fine i guess
