### ISSUE TITLE
[BUG] Steb is bad

### ISSUE THREAD

**Issue by Pexku789** [WurstPlus/wurst-plus-three#225]
**Describe the bug**
Well, its not a bug more like a thing to fix. See screenshots* 

**Expected behavior**
Well, you should be able to step dous

**Screenshots**
Add screenshots or videos to help explain the problem.
http://i.imgur.com/gb5imnd.png - Can be stepped
http://i.imgur.com/hpjpvCL.png - Can not be stepped

**Comment by wallhacks0** [comment]
its step with a p but do you mean the issue is that you cant step around blocks?

**Comment by Pexku789** [comment]
You cant steb to the gap, like shown in the pictures.

**Comment by wallhacks0** [comment]
Are we talking about reverse step?

**Comment by Teddyymc** [comment]
Step doesn't work at some y level close to the nether roof and at y1

**Comment by Teddyymc** [comment]
Why closing this issue ?

**Comment by pwn3r1** [comment]
hey, whats Steb? is this a new module i dont know about?

**Comment by Pexku789** [comment]
Steb ks bein gad pitezs 🤣🤣🤣
