### ISSUE TITLE
Auto dupe

### ISSUE THREAD

**Issue by Hub35TheBestCpvper** [WurstPlus/wurst-plus-three#232]
Auto dupe just randomly turns on and crashes me

**Comment by ProfKambing** [comment]
can you provide crash log...

**Comment by Hub35TheBestCpvper** [comment]
> can you provide crash log...

[latest.log](https://github.com/WurstPlus/wurst-plus-three/files/6836748/latest.log)

**Comment by Madmegsox1** [comment]
not functinal
