### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by wallhacks0** [WurstPlus/wurst-plus-three#235]
@TrvsF @Madmegsox1  I have no access to my discord for like a day but i made phade rendering, the update removed chainmode and thread tho should I still push it?

**Comment by Pexku789** [comment]
stfu

**Comment by amongusenjoyer69** [comment]
I have no access to my discord for like a day but i made phade rendering, the update removed chainmode and thread tho should I still push it?

**Comment by chocopie69** [comment]
im black

**Comment by amongusenjoyer69** [comment]
@chocopie69 black chocoate b=pie
