### ISSUE TITLE
add auto maxor is cute module 

### ISSUE THREAD

**Issue by maxorenjoysnekos** [WurstPlus/wurst-plus-three#236]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chocopie69** [comment]
are you retarded

**Comment by amongusenjoyer69** [comment]
> are you retarded

having 69 with chocolate pie.

**Comment by chocopie69** [comment]
> > are you retarded
> 
> having 69 with chocolate pie.

having fun with you`re mom

**Comment by amongusenjoyer69** [comment]
> > > are you retarded
> > 
> > 
> > having 69 with chocolate pie.
> 
> having fun with you`re mom

let’s have fun with mom together
