### ISSUE TITLE
this client is a joke

### ISSUE THREAD

**Issue by 9mq** [WurstPlus/wurst-plus-three#237]
:joy:

**Comment by wallhacks0** [comment]
ur issue is a joke

**Comment by amongusenjoyer69** [comment]
> 😂

true. has bitcoin minor. phobos incident except 2021. travis log chrome password too. crystlainqq rat phobos 2.0. ii prank. wp3 fake. wp2 is real but private. emperium play among us sus. they watch club penguin in vc. 9mq is truth teller. anarchy prophocey. bane of anarchy,. robot meta. burrow. pyro client excit scam. impact and future safe. fitmc makes content. fitmc bald. fitmc popbob hausemaster fanfiction. pedo. teen. predator. anarhchy arrested. swatted. doxxed. anarchy not good.

**Comment by chocopie69** [comment]
We do not allow hacking in any server. This client is meant to log chrome datas, femboy porn stash coords, onlyfans account password (we will expose you for simping), browsing history, cps and much more. DO NOT use it on any servers!

**Comment by amongusenjoyer69** [comment]
> We do not allow hacking in any server. This client is meant to log chrome datas, femboy porn stash coords, onlyfans account password (we will expose you for simping), browsing history, your cp images and much more. DO NOT use it on any servers!

why do you want my cheese pizza pics

**Comment by chocopie69** [comment]
> > We do not allow hacking in any server. This client is meant to log chrome datas, femboy porn stash coords, onlyfans account password (we will expose you for simping), browsing history, your cp images and much more. DO NOT use it on any servers!
> 
> why do you want my cheese pizza pics

not cheese pizza retard. cp stands for cock penis. i want your cock penis pics
