### ISSUE TITLE
funny bug[BUG]

### ISSUE THREAD

**Issue by amongusenjoyer69** [WurstPlus/wurst-plus-three#238]
funny. switch fast mode to none. turn on ca. game crash. boom. explode.

**Comment by chocopie69** [comment]
its bcz the ca is too fast that the game cant handle it
the only way to fix the funny is to stop the funny (aka changing the event system, dont use the built-in event system, use mixins nogger)

**Comment by amongusenjoyer69** [comment]
> its bcz the ca is too fast that the game cant handle it
> the only way to fix the funny is to stop the funny (aka changing the event system, dont use the built-in event system, use mixins nogger)

thanks fellow nogger

**Comment by Madmegsox1** [comment]
send crash log

**Comment by wallhacks0** [comment]
send crashlog on discord
