### ISSUE TITLE
0.7.0 ca crashes my game

### ISSUE THREAD

**Issue by JayH4x** [WurstPlus/wurst-plus-three#241]
😞

**Comment by amongusenjoyer69** [comment]
send config noobe

**Comment by JayH4x** [comment]
[Crystal Aura.txt](https://github.com/WurstPlus/wurst-plus-three/files/6889372/Crystal.Aura.txt)
its not configured properly but here

**Comment by JayH4x** [comment]
[nexxors sex cumfig.zip](https://github.com/WurstPlus/wurst-plus-three/files/6889394/nexxors.sex.cumfig.zip)
heres my entire config if u want

**Comment by wallhacks0** [comment]
send crashlog to wallhacks#6969
