### ISSUE TITLE
[BUG]Game crashes on startup when mixed with other mods

### ISSUE THREAD

**Issue by maxgamesNL** [WurstPlus/wurst-plus-three#242]
**Describe the bug**
The Client crashes on startup when mixed with other mods

**To Reproduce**
Install other mods(the ones I use are: Impact, Inertia, Kami Blue and OptiFine_1.12.2_HD_U_G5.

**Expected behavior**
It should start up but it doesnt.

**Additional context**
It is launched from multimc. But also happens when launched from Minecraft launcher.

I will add the crash log as a file
[crashlog.txt](https://github.com/WurstPlus/wurst-plus-three/files/6886791/crashlog.txt)

**Comment by HappyGibbons** [comment]
btw you should use v0.7.0

**Comment by maxgamesNL** [comment]
> btw you should use v0.7.0

Is that already done then? because it isn't in the releases. 
if it is out of dev then I can just build it

**Comment by HappyGibbons** [comment]
https://github.com/WurstPlus/wurst-plus-three/tree/0.7.0

**Comment by wallhacks0** [comment]
maxgamesnl wat een naam lol

**Comment by maxgamesNL** [comment]
> maxgamesnl wat een naam lol

ja toch

**Comment by maxgamesNL** [comment]
> https://github.com/WurstPlus/wurst-plus-three/tree/0.7.0

Thx, this was what I needed. It works with other mods now. Was a bit of work to get working but now I got it.
