### ISSUE TITLE
a somewhat better viewmodel

### ISSUE THREAD

**Issue by Gaamr** [WurstPlus/wurst-plus-three#243]
the viewmodel is kind of weird, I really like the customization but whenever a gapple is close to the center, when you eat it goes off screen, and its pretty annoying to see that

I've seen this in gamesense where whenever you eat a gapple its somewhat near where you normally eat it and its on screen

maybe looking at what gamesense did, and either taking the code or recreating it

1: trying to eat with centered viewmodel (gapple is offscreen because of what I said above)
![2021-07-27_19 44 32](https://user-images.githubusercontent.com/83148885/127241687-ad909800-4ff6-415b-a593-3d01bfdbae68.png)

2: eating gapple with gamesense viewmodel (config looks weird because it isn't what I normally used when I used gamesense viewmodel)
![2021-07-27_19 46 42](https://user-images.githubusercontent.com/83148885/127241695-8982f8d1-73d6-4e76-a0ff-055cbf4a03c4.png)

**Comment by wallhacks0** [comment]
config better

**Comment by chocopie69** [comment]
config issue

**Comment by Gaamr** [comment]
> config better

Not even a config issue try it, gapple goes across the screen
