### ISSUE TITLE
[QUESTION] Can't find 0.70 download

### ISSUE THREAD

**Issue by Fiyxz** [WurstPlus/wurst-plus-three#245]
**Question**
When i go to the releases/tags it only goes up to 0.62 were can i find the 0.70 get back to me on discord if you can Fiyxz#8118

**Comment by maxgamesNL** [comment]
The 0.7.0 release isn't fully out yet.
It is stable but not done. So if you want it you will need to build it yourself. You need the java 8 JDK and then clone the repository to a location. Then copy the location and open a powershell window.
Type cd (and then the location of the folder) 
Then run the commands in the readme file

**Comment by Fiyxz** [comment]
Where is the download link to build it?

**Comment by maxgamesNL** [comment]
> Where is the download link to build it?

You need to open powershell somewhere and type: git clone -b 0.7.0 https://github.com/WurstPlus/wurst-plus-three 

That will download it.
Then run the commands in the readme file

**Comment by Fiyxz** [comment]
Thanks

**Comment by HappyGibbons** [comment]
yes

**Comment by maxgamesNL** [comment]
> yes
> 

Did it work? Then you can find the jar in build/libs

**Comment by HappyGibbons** [comment]
it did work

**Comment by maxgamesNL** [comment]
> it did work
> 

It should
