### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by furiousssss** [WurstPlus/wurst-plus-three#246]
**Is your feature request related to a problem? Please describe.**
no it isn't
**Describe the solution you'd like**
It's a module called suck my balls 
I want it to eat my balls 
**Describe alternatives you've considered**
It eats my balls 
**Additional context**
Balls

**Comment by TediousDuskFall** [comment]
This is a very interesting improvement you suggest. May I ask why you would want your testicles consumed?
