### ISSUE TITLE
TotemPopChameleons - [SUGGESTION]

### ISSUE THREAD

**Issue by amongusenjoyer69** [WurstPlus/wurst-plus-three#251]
**Is your feature request related to a problem? Please describe.**
On a sunny, cloudless morning, when I turn on my personal computer, log onto the Minecraft: Java Edition launcher and select my 1.12.2 Forge directory, I feel an inexplicable frustration knowing that there is no Totem Pop Chameleon hack within my favorite public client, "Wurst Plus Three". It genuinely ruins my day, let alone my hacker versus hacker experience; it makes me want to use another client and sometimes even forces me to play another game. 

**Describe the solution you'd like**
I would like a Totem Pop Chameleon module to be implemented within the fantastic client that we all know as "Wurst Plus Three". It involves a player succeeding the lowest amount of health but with a totem in their main/offhand, thus making them "pop" this totem. The module should then render this unfortunate occurence using a chameleon hack - highlighting the player that had just lost their precious, life-saving item. 

**Describe alternatives you've considered**
Having had suicidal thoughts recently, I would have no choice but to terminate my life if the client "Wurst Plus Three" did not incorporate such a wonderful render module into its long list of helpful utility modifications. 

**Additional context**
To those of you who are against the issue published: you do not breathe oxygen.

**Comment by upapu** [comment]
lmfao

**Comment by Ozynt** [comment]
bruh

**Comment by HappyGibbons** [comment]
i eat people

**Comment by k6w** [comment]
black people have better ideas

**Comment by Madmegsox1** [comment]
Soon
