### ISSUE TITLE
[SUGGESTION] Smart Offhand totem switch

### ISSUE THREAD

**Issue by chocopie69** [WurstPlus/wurst-plus-three#252]
**Is your feature request related to a problem? Please describe.**
Sometimes when it needs to switch to a totem it doesnt and I instantly died because the crystal damage is higher than the hp switch setting

**Describe the solution you'd like**
A smart option which will check for all crystals, and if one deals more damage than your current health then switch to totem

**Comment by chocopie69** [comment]
yo can anyone take a look

**Comment by TediousDuskFall** [comment]
this is basically what crystalcheck should do except its broken and doesnt do anything

jmonkey
