### ISSUE TITLE
ca[SUGGESTION]

### ISSUE THREAD

**Issue by ghost** [WurstPlus/wurst-plus-three#258]
hole prior 
- crystals people when they jump in their holes
- make this a separate range 

make place feet obby more obsidian efficient
- places less obsidian 
- just as effective

antiweakness silent switch
- silentswitches a weapon/tool when under influence of weakness

better raytracing
- even better placements

make dmgs and predict ticks floats
- more customization

fix ca placing blocks when you hold them in your hand
- annoying for terrain duels 

publicly release 0.7.0 
- i hate building every commit

**Comment by Madmegsox1** [comment]
Ticks cannot be a double or a floating point value, as the game counts ticks in a int value, clients that have this feature don't actually count it as a floating point value, they cast it to a int value

**Comment by amongusenjoyer69** [comment]
> Ticks cannot be a double or a floating point value, as the game counts ticks in a int value, clients that have this feature don't actually count it as a floating point value, they cast it to a int value

whoops didn’t even release that
