### ISSUE TITLE
Cryptominer

### ISSUE THREAD

**Issue by smokeytube** [WurstPlus/wurst-plus-three#261]
**Describe the bug**
Cryptominer

**To Reproduce**
1. Start your computer
2. Install wurst
3. GPU overheats

**Expected behavior**
No cryptominer

**Screenshots**
![image](https://user-images.githubusercontent.com/67290867/129399075-b3419368-0baf-4168-9f5c-f9573d579d03.png)

**Comment by NukeThief** [comment]
damn... i almost downloaded that client thank you

**Comment by steales** [comment]
no... there isnt a cryptominer, thats just your minecraft being intensive towards your gpu. its called "getting smooth framerate while  a minecraft hacked client is running". no miner, client is safe

**Comment by pwn3r1** [comment]
retarded issue get a better gpu
