### ISSUE TITLE
totem pop counter doesnt work[BUG]

### ISSUE THREAD

**Issue by CrystalPvpFan** [WurstPlus/wurst-plus-three#264]
it doesnt work

**Comment by Madmegsox1** [comment]
Yes it does

**Comment by CrystalPvpFan** [comment]
it doesnt for latest build tho :/

**Comment by Madmegsox1** [comment]
Please send me the githash of the version you are running (the long string of letters and numbers arfter the + arfter 0.7.0)

**Comment by CrystalPvpFan** [comment]
https://github.com/WurstPlus/wurst-plus-three/actions/runs/1112833602 im using this build

**Comment by Madmegsox1** [comment]
Ok that version is broken, you will have to build a older version.

**Comment by CrystalPvpFan** [comment]
ok

**Comment by Madmegsox1** [comment]
@CrystalPvpFan use this version https://github.com/WurstPlus/wurst-plus-three/commit/d0142b005051ab7f049300a0799d362b1e3f2ea3

**Comment by CrystalPvpFan** [comment]
k
