### ISSUE TITLE
[QUESTION] AutoClip

### ISSUE THREAD

**Issue by kubamolna** [WurstPlus/wurst-plus-three#265]
**Question**
where do i find the clips?

**Comment by jewbob** [comment]
SHUT UP!

**Comment by kubamolna** [comment]
lol where

**Comment by CrystalPvpFan** [comment]
its in ur ass

**Comment by MysticDevYT** [comment]
download any clipping software ( like medal.tv ) and set the bind to ur clipping bind that u set in the clipping software

> **Question**
> where do i find the clips?

**Comment by Madmegsox1** [comment]
@MysticDevYT  Thank you for answering this question
