### ISSUE TITLE
Array List issue[BUG]

### ISSUE THREAD

**Issue by CrystalPvpFan** [WurstPlus/wurst-plus-three#269]
So when u have kill aura on and go near a person with a long name, array list position changes like it goes off the screen

**Comment by Madmegsox1** [comment]
What version are you using?

**Comment by CrystalPvpFan** [comment]
> What version are you using?

https://github.com/WurstPlus/wurst-plus-three/commit/d0142b005051ab7f049300a0799d362b1e3f2ea3

**Comment by CrystalPvpFan** [comment]
i'll record a video

**Comment by CrystalPvpFan** [comment]
https://user-images.githubusercontent.com/86374191/131543025-b927f060-fabe-47f9-baad-b428478f7cd6.mp4

**Comment by Madmegsox1** [comment]
oh wtf lol

**Comment by Madmegsox1** [comment]
just do .drawn kill_aura

**Comment by CrystalPvpFan** [comment]
kk
