### ISSUE TITLE
[SUGGESTION] Fade

### ISSUE THREAD

**Issue by goztb22** [WurstPlus/wurst-plus-three#270]
**Is your feature request related to a problem? Please describe.**
its not problem[...]

**Describe the solution you'd like**
Fade in ca like xulu smooth esp or leux beta0.9-8 beta or phobos ya know

**Describe alternatives you've considered**
like just animation for ca render

**Additional context**
https://youtu.be/ygoRmITUPFs example of it :/

**Comment by wallhacks0** [comment]
Already in the client

**Comment by goztb22** [comment]
oh fine
