### ISSUE TITLE
[QUESTION] what the fuck is this

### ISSUE THREAD

**Issue by mmmaxcode** [WurstPlus/wurst-plus-three#272]
https://github.com/WurstPlus/wurst-plus-three/blob/main/src/main/java/me/travis/wurstplusthree/mixin/mixins/MixinEntity.java

this gives me a headache. ever heard of mixins???????????????????????????????????????????????

@Madmegsox1 please fix thsi cus its like actualluy retarded

**Comment by zopac** [comment]
why phobos

**Comment by Madmegsox1** [comment]
Wtf is that mixin xd

**Comment by wallhacks0** [comment]
Pasted from phobos not our code

**Comment by mmmaxcode** [comment]
> Wtf is that mixin xd

exactly my point (dont paste decompiled clients lol)

**Comment by Madmegsox1** [comment]
https://github.com/WurstPlus/wurst-plus-three/blob/0.7.0/src/main/java/me/travis/wurstplusthree/mixin/mixins/MixinEntity.java

it is fixed in 0.7.0
