### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Critbringr** [WurstPlus/wurst-plus-three#282]
**Question**
Ask your question and include as much relevant information as possible.
ok, so where is the armor status hud mod, i do not see it in the click gui thingy.

**Comment by WMSGaming** [comment]
> **Question** Ask your question and include as much relevant information as possible. ok, so where is the armor status hud mod, i do not see it in the click gui thingy.

in hud editor

**Comment by Critbringr** [comment]
i am a dumbass, what command pulls up hud list

**Comment by Critbringr** [comment]
i am not kidding when i day im a dumbass, which category of the gui

**Comment by Critbringr** [comment]
which category tho, i have all of them open
