### ISSUE TITLE
crashing when joining server

### ISSUE THREAD

**Issue by Solidbeast42** [WurstPlus/wurst-plus-three#283]
whenever i join a server it says joining server than the minecraft window goes black for maybe 1 second an then it crahses
[crash-2021-04-04_17.46.04-client.txt](https://github.com/WurstPlus/wurst-plus-three/files/7318411/crash-2021-04-04_17.46.04-client.txt)

**Comment by RealzPrestige** [comment]
get a brain then come back

**Comment by TrvsF** [comment]
lmao
