### ISSUE TITLE
w+3 crashing

### ISSUE THREAD

**Issue by Keplerqq** [WurstPlus/wurst-plus-three#288]
So im using w+3 with lambda client and w+3 is crashing. How to fix this?

**Comment by Keplerqq** [comment]
![mods](https://user-images.githubusercontent.com/87177200/141645430-b1ee356f-f4e4-4192-b0a4-2706cbda13c0.png)


my mods folder

**Comment by WMSGaming** [comment]
remove postman

**Comment by Keplerqq** [comment]
> remove postman

everything works thanks
