### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by creepylenain732** [WurstPlus/wurst-plus-three#296]
helllo i cant build client myself...
plz repair it thatks

**Comment by sarnthilIsHorny** [comment]
skill issue

**Comment by creepylenain732** [comment]
I just malle
gradlew setupdecompworkspace
gradlew clean
gradlew build
And at all processes error

Dne po 3. 1. 2022 7:14 uživatel sarnthilx0 ***@***.***>
napsal:
