### ISSUE TITLE
[BUG] do you know why i get kicked when i have my delays at 0 and i get kicked from server when i cpvp

### ISSUE THREAD

**Issue by eimaaat** [WurstPlus/wurst-plus-three#297]
**Describe the bug**

**To Reproduce**
1. Turn on module: '...'
2. Set the setting to '....'
3. See error

**Expected behavior**

**Screenshots**
Add screenshots or videos to help explain the problem.

**Additional context**

**Comment by deanroks1** [comment]
what you get kicked for like clicking to fast or kicked for no reason if no reason then its prob cuz your ping is to high for your break speed and then its spam hitting it and then you get kicked

Set settings to Delay everything above 10

**Comment by sarnthilIsHorny** [comment]
nn
