### ISSUE TITLE
[BUG] not compatible with viaforge

### ISSUE THREAD

**Issue by FIonderr** [WurstPlus/wurst-plus-three#98]
**Describe the bug**
Anytime I run wp3 and viaforge it crashes

**To Reproduce**
drag viaforge in
start game
exit code 0

**Expected behavior**
game should open and work

**Comment by BiGgweeb** [comment]
That is odd. version 20w45a works perfectly fine and has 1.17 support, but the newest does not work with it. I recreated the crash and I tried to check the logs, but nothing showed up.
https://www.curseforge.com/minecraft/mc-mods/viaforge/files/3124719
Here is the link to the one I use, it should not crash. We will look into it in the meantime.
