### ISSUE TITLE
[SUGGESTION] will there be a fabric port?

### ISSUE THREAD

**Issue by ShayMDOS** [WurstPlus/wurst-plus-three#99]
I was wondering if there will be a port for fabric since it runs smoother and Wurst v7 only runs best on fabric now.

**Comment by Madmegsox1** [comment]
@TrvsF  LOL

**Comment by A663S** [comment]
XD

**Comment by Officer32k** [comment]
LOL @ShayMDOS ....no
but ur so funny :D
